### ISSUE TITLE
Table.write does not know how to deal with foreign keys

### ISSUE THREAD

**Issue by Anaphory** [clld/clldutils#55]
Foreign key specifications do not have a `.header` (instead, they can be multiple columns, described by `columnReference`, if I understand http://w3c.github.io/csvw/metadata/#dfn-foreign-key-definition correctly). I think that one also says that other properties (`.virtual`) should not exist?

https://github.com/clld/clldutils/blob/2d524d246b96b9a96ade428df422af1c0d60d1b8/clldutils/csvw/metadata.py#L490

Aditionally, `Table.write` passes data writing to its columns' `.write` method. Foreign keys don't implement that method, and it might be hard to implement anyway because in the general case it outputs more than one column, if I get it correctly.

**Comment by xrotwang** [comment]
Yes, the w3c spec support composite foreign keys. Generally, I think, it is best to not regard "foreign key" as some sort of column type, but follow the "constraint" paradigm: i.e. "foreign keys" is a list of constraints on the values of a row, rather than a core property of the individual columns. Thus it shouldn't interfere with writing at all,  but will come into play only when calling a dataset's `validate` method.

**Comment by xrotwang** [comment]
So if we want to add more support for handling of foreign keys, we may want to introduce `Constraint` objects, pretty much like SQLAlchemy does it.

**Comment by Anaphory** [comment]
How are you currently handling foreign keys to `languages.csv` etc.? I could not find an example and have therefore no idea what they should look like

**Comment by Anaphory** [comment]
Ah, now I see. I shall adapt the script I sent you.
